"""
CurricuForge — JSON Exporter
Takes curriculum JSON from ai_engine.py and exports it
as a clean, structured, LMS-ready JSON file.

Supports:
- Raw export (exact AI output)
- LMS-ready export (Moodle/Canvas compatible structure)
- Summary export (lightweight version for marketing/admissions)
"""

import json
import io
from datetime import datetime


# ─────────────────────────────────────────
# EXPORT FORMAT 1 — RAW EXPORT
# Exact curriculum JSON as returned by ai_engine.py
# ─────────────────────────────────────────

def export_raw(curriculum: dict) -> bytes:
    """
    Returns the curriculum exactly as generated by AI.
    Clean, indented JSON — ready for any downstream use.

    Usage in Streamlit:
        st.download_button("Download JSON", export_raw(curriculum), "curriculum.json")
    """

    output = {
        "exported_by": "CurricuForge",
        "powered_by": "IBM Granite 3.3 2B via Ollama",
        "export_type": "raw",
        "exported_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "curriculum": curriculum
    }

    return json.dumps(output, indent=2, ensure_ascii=False).encode("utf-8")


# ─────────────────────────────────────────
# EXPORT FORMAT 2 — LMS READY EXPORT
# Restructured for Moodle / Canvas / Google Classroom
# ─────────────────────────────────────────

def export_lms_ready(curriculum: dict) -> bytes:
    """
    Restructures curriculum into LMS-compatible format.
    Ready for direct import into Moodle, Canvas, or Google Classroom.

    Structure:
    - course_catalog[]     → flat list of all courses across all semesters
    - learning_outcomes[]  → extracted from topics
    - credit_summary       → total credits calculation
    """

    course_catalog   = []
    total_credits    = 0
    total_courses    = 0

    for semester in curriculum.get("semesters", []):
        sem_num   = semester.get("semester_number", 0)
        sem_title = semester.get("semester_title", "")

        for course in semester.get("courses", []):
            credits_raw = course.get("credits", 4)
            credits = int(credits_raw) if isinstance(credits_raw, (int, float, str)) else 4
            total_credits += credits  # type: ignore
            total_courses += 1  # type: ignore

            course_catalog.append({
                "id":               course.get("course_code", ""),
                "title":            course.get("course_name", ""),
                "semester":         sem_num,
                "semester_title":   sem_title,
                "credits":          credits,
                "hours_per_week":   course.get("hours_per_week", 3),
                "description":      course.get("description", ""),
                "learning_outcomes": [
                    f"Understand and apply {topic}"
                    for topic in course.get("topics", [])
                ],
                "topics": course.get("topics", []),
                "lms_metadata": {
                    "course_type":   "core",
                    "delivery_mode": "in_person",
                    "assessment":    ["assignments", "midterm", "final_exam"],
                    "language":      "English"
                }
            })

    capstone = curriculum.get("capstone_project", {})

    lms_output = {
        "exported_by":   "CurricuForge",
        "powered_by":    "IBM Granite 3.3 2B via Ollama",
        "export_type":   "lms_ready",
        "exported_at":   datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "lms_format":    "generic_v1",
        "program": {
            "title":           curriculum.get("curriculum_title", ""),
            "level":           curriculum.get("level", ""),
            "domain":          curriculum.get("skill_domain", ""),
            "industry_focus":  curriculum.get("industry_focus", ""),
            "total_semesters": curriculum.get("total_semesters", 0),
            "weekly_hours":    curriculum.get("weekly_hours", 0),
        },
        "credit_summary": {
            "total_courses":       total_courses,
            "total_credits":       total_credits,
            "credits_per_course":  4,
            "hours_per_week":      3,
        },
        "course_catalog": course_catalog,
        "capstone_project": {
            "title":       capstone.get("title", ""),
            "description": capstone.get("description", ""),
            "credits":     8,
            "semester":    curriculum.get("total_semesters", 0),
        }
    }

    return json.dumps(lms_output, indent=2, ensure_ascii=False).encode("utf-8")


# ─────────────────────────────────────────
# EXPORT FORMAT 3 — SUMMARY EXPORT
# Lightweight version for admissions / marketing
# ─────────────────────────────────────────

def export_summary(curriculum: dict) -> bytes:
    """
    Lightweight summary export — ideal for:
    - Admissions brochures
    - Marketing materials
    - Quick institutional overview
    """

    semesters_summary = []

    for semester in curriculum.get("semesters", []):
        course_names = [
            c.get("course_name", "") 
            for c in semester.get("courses", [])
        ]
        semesters_summary.append({
            "semester":   semester.get("semester_number", 0),
            "title":      semester.get("semester_title", ""),
            "courses":    course_names,
            "total_courses": len(course_names),
            "total_credits": len(course_names) * 4
        })

    capstone = curriculum.get("capstone_project", {})

    summary_output = {
        "exported_by":  "CurricuForge",
        "export_type":  "summary",
        "exported_at":  datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "program_title": curriculum.get("curriculum_title", ""),
        "level":         curriculum.get("level", ""),
        "domain":        curriculum.get("skill_domain", ""),
        "industry":      curriculum.get("industry_focus", ""),
        "duration":      f"{curriculum.get('total_semesters', 0)} Semesters",
        "weekly_hours":  curriculum.get("weekly_hours", 0),
        "semesters":     semesters_summary,
        "capstone":      capstone.get("title", ""),
        "total_courses": sum(
            len(s.get("courses", [])) 
            for s in curriculum.get("semesters", [])
        ),
        "total_credits": sum(
            len(s.get("courses", [])) * 4
            for s in curriculum.get("semesters", [])
        )
    }

    return json.dumps(summary_output, indent=2, ensure_ascii=False).encode("utf-8")


# ─────────────────────────────────────────
# MAIN EXPORT FUNCTION
# Called by Streamlit — returns all 3 formats
# ─────────────────────────────────────────

def export_all(curriculum: dict) -> dict:
    """
    MAIN FUNCTION — called by Streamlit app.

    Returns all 3 export formats as bytes.

    Usage in Streamlit:
        exports = export_all(result["curriculum"])

        st.download_button("Raw JSON",     exports["raw"],     "curriculum_raw.json")
        st.download_button("LMS JSON",     exports["lms"],     "curriculum_lms.json")
        st.download_button("Summary JSON", exports["summary"], "curriculum_summary.json")
    """

    return {
        "raw":     export_raw(curriculum),
        "lms":     export_lms_ready(curriculum),
        "summary": export_summary(curriculum)
    }


# ─────────────────────────────────────────
# QUICK TEST (run directly: python json_exporter.py)
# ─────────────────────────────────────────

if __name__ == "__main__":

    sample = {
        "curriculum_title": "BTech in Machine Learning (AI focused)",
        "level": "BTech",
        "skill_domain": "Machine Learning",
        "industry_focus": "AI",
        "total_semesters": 2,
        "weekly_hours": 20,
        "semesters": [
            {
                "semester_number": 1,
                "semester_title": "Fundamentals",
                "courses": [
                    {
                        "course_code": "CS101",
                        "course_name": "Intro to ML",
                        "credits": 4,
                        "hours_per_week": 3,
                        "description": "Introduction to machine learning.",
                        "topics": ["Supervised Learning", "Unsupervised Learning", "Neural Networks"]
                    },
                    {
                        "course_code": "CS102",
                        "course_name": "Mathematics for ML",
                        "credits": 4,
                        "hours_per_week": 3,
                        "description": "Math foundations for ML.",
                        "topics": ["Linear Algebra", "Calculus", "Probability"]
                    }
                ]
            }
        ],
        "capstone_project": {
            "title": "ML Capstone Project",
            "description": "A real world ML project evaluated by industry professionals."
        }
    }

    print("=" * 50)
    print("CurricuForge JSON Exporter — Test Run")
    print("=" * 50)

    exports = export_all(sample)

    # Save all 3 formats
    for name, data in exports.items():
        filename = f"test_export_{name}.json"
        with open(filename, "wb") as f:
            f.write(data)
        parsed = json.loads(data)
        print(f"\n✅ {name.upper()} export — {len(data):,} bytes → {filename}")

        if name == "lms":
            print(f"   Total courses in catalog: {len(parsed['course_catalog'])}")
            print(f"   Total credits: {parsed['credit_summary']['total_credits']}")
        elif name == "summary":
            print(f"   Total courses: {parsed['total_courses']}")
            print(f"   Total credits: {parsed['total_credits']}")

    print("\n🎉 All 3 JSON exports generated successfully!")